language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk7
#  - openjdk7
notifications:
  email:
    on_success: never
    on_failure: always
  irc: "irc.freenode.org#cilib"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb13cbe56247a955e805
    on_success: always
    on_failure: always
    on_start: false
