title: CIlib
tagline: Type-safe Computational Intelligence
url: http://cilib.net
paginate: 1
permalink: pretty
#markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
#  syntax_highlighter: rouge

baseurl: ""
apidocs: /api/

gems: [jekyll-paginate, jekyll-gist]

collections:
  tut:
    output: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             :compressed

# Custom vars
version:             1.0
github:
  repo:              https://github.com/cirg-up/cilib
